### ISSUE TITLE
CSS vars "undefined and used without a fallback"

### ISSUE THREAD

**Issue by thompsongl** [basscss/customize#1]
At compilation, local variables in a few modules never get defined (despite definitions in the source CSS), so PostCSS outputs the var() reference instead.

No errors, just some warnings:
![screen shot 2015-06-19 at 9 04 00 am](https://cloud.githubusercontent.com/assets/2728212/8255387/425f29be-1665-11e5-9974-c89aeeb919ce.png)

Possible that this has more to do with [jxnblk/custom-css](https://github.com/jxnblk/custom-css)

**Comment by jxnblk** [comment]
Yeah, I definitely need to clean up this customize app and the `custom-css` module. Thanks for the heads up!
